/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfreservasg1;

import javax.swing.JFrame;

/**
 *
 * @author allis
 */
public class VentanaAdministrador extends javax.swing.JFrame {
    private Administrador administrador;
    private JFrame menuPrincipal;
    
    
    public VentanaAdministrador( Administrador administrador, JFrame menuPrincipal) {
        initComponents();
        this.administrador = administrador;
        this.menuPrincipal = menuPrincipal;
        setTitle("Gestión Administrador");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVerCantidadReservas = new javax.swing.JButton();
        btnRankingAreas = new javax.swing.JButton();
        btnEditarReserva = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 231, 149));

        btnVerCantidadReservas.setBackground(new java.awt.Color(0, 153, 102));
        btnVerCantidadReservas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVerCantidadReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerCantidadReservas.setText("Ver Cantidad de Reservas");
        btnVerCantidadReservas.setBorderPainted(false);
        btnVerCantidadReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerCantidadReservas.setFocusPainted(false);
        btnVerCantidadReservas.setOpaque(true);
        btnVerCantidadReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCantidadReservasActionPerformed(evt);
            }
        });

        btnRankingAreas.setBackground(new java.awt.Color(0, 204, 204));
        btnRankingAreas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnRankingAreas.setForeground(new java.awt.Color(255, 255, 255));
        btnRankingAreas.setText("Áreas mas Usadas");
        btnRankingAreas.setBorderPainted(false);
        btnRankingAreas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRankingAreas.setFocusPainted(false);
        btnRankingAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingAreasActionPerformed(evt);
            }
        });

        btnEditarReserva.setBackground(new java.awt.Color(255, 153, 153));
        btnEditarReserva.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnEditarReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarReserva.setText("Editar una Reserva");
        btnEditarReserva.setBorderPainted(false);
        btnEditarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarReserva.setFocusPainted(false);
        btnEditarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarReservaActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(102, 102, 102));
        btnVolver.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver al Menu Principal");
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setFocusPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRACIÓN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRankingAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerCantidadReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(btnEditarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnVerCantidadReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRankingAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCantidadReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCantidadReservasActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);//para ocultar la ventana de los botones
         administrador.mostrarCantidadReserva();
         this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnVerCantidadReservasActionPerformed

    private void btnRankingAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingAreasActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);//para ocultar la ventana de los botones
        administrador.mostrarRankingAreas();
         this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnRankingAreasActionPerformed

    private void btnEditarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarReservaActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);//para ocultar la ventana de los botones
         administrador.editarReserva();
          this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnEditarReservaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
          menuPrincipal.setVisible(true);
          this.dispose(); // Cierra esta ventana
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarReserva;
    private javax.swing.JButton btnRankingAreas;
    private javax.swing.JButton btnVerCantidadReservas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
