/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfreservasg1;

import javax.swing.JFrame;

/**
 *
 * @author allis
 */
public class VentanaReservas extends javax.swing.JFrame {
     private Reservas reservas;
     private JFrame menuPrincipal;
     
     
    /**
     * Creates new form VentanaReservas
     */
    public VentanaReservas( Reservas reservas, JFrame menuPrincipal) {
        initComponents();
        this.reservas = reservas;
        this.menuPrincipal = menuPrincipal;
        setLocationRelativeTo(null);
        setTitle("Gestión de Reservas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnEspacioTrabajo = new javax.swing.JButton();
        btnCubiculo = new javax.swing.JButton();
        btnAuditorio = new javax.swing.JButton();
        btnRecreacion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVerEstado = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout());

        jPanel3.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.EmptyEditorArea.background"));

        btnEspacioTrabajo.setBackground(new java.awt.Color(0, 123, 255));
        btnEspacioTrabajo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnEspacioTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        btnEspacioTrabajo.setText("Reservar Espacio de Trabajo");
        btnEspacioTrabajo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEspacioTrabajo.setBorderPainted(false);
        btnEspacioTrabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEspacioTrabajo.setFocusPainted(false);
        btnEspacioTrabajo.setOpaque(true);
        btnEspacioTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspacioTrabajoActionPerformed(evt);
            }
        });

        btnCubiculo.setBackground(new java.awt.Color(40, 167, 69));
        btnCubiculo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCubiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnCubiculo.setText("Reservar Cubiculo");
        btnCubiculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCubiculo.setBorderPainted(false);
        btnCubiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCubiculo.setFocusPainted(false);
        btnCubiculo.setOpaque(true);
        btnCubiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubiculoActionPerformed(evt);
            }
        });

        btnAuditorio.setBackground(new java.awt.Color(111, 62, 90));
        btnAuditorio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAuditorio.setForeground(new java.awt.Color(255, 255, 255));
        btnAuditorio.setText("Reservar Auditorio");
        btnAuditorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAuditorio.setBorderPainted(false);
        btnAuditorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuditorio.setFocusPainted(false);
        btnAuditorio.setOpaque(true);
        btnAuditorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditorioActionPerformed(evt);
            }
        });

        btnRecreacion.setBackground(new java.awt.Color(0, 204, 204));
        btnRecreacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnRecreacion.setForeground(new java.awt.Color(255, 255, 255));
        btnRecreacion.setText("Reservar un Espacio de Recreacion");
        btnRecreacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRecreacion.setBorderPainted(false);
        btnRecreacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecreacion.setFocusPainted(false);
        btnRecreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecreacionActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(220, 53, 69));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar Reserva");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setBorderPainted(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVerEstado.setBackground(new java.awt.Color(108, 117, 125));
        btnVerEstado.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVerEstado.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEstado.setText("Ver Estado de las Reservas");
        btnVerEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerEstado.setBorderPainted(false);
        btnVerEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerEstado.setFocusPainted(false);
        btnVerEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadoActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(52, 58, 64));
        btnVolver.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver al Menu Principal");
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setFocusPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reservas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRecreacion, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(btnAuditorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCubiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEspacioTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEspacioTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCubiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAuditorio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        menuPrincipal.setVisible(true);
        this.dispose(); // Cierra esta ventana
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVerEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);//para ocultar la ventana de los botones
        reservas.verEstadoReservas();
        this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnVerEstadoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);//para ocultar la ventana de los botones
        reservas.cancelarReserva();
        this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRecreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecreacionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);//para ocultar la ventana de los botones
        reservas.reservarEspacioRecreacion();
        this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnRecreacionActionPerformed

    private void btnAuditorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditorioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);//para ocultar la ventana de los botones
        reservas.reservarAuditorio();
        this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnAuditorioActionPerformed

    private void btnCubiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubiculoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);//para ocultar la ventana de los botones
        reservas.reservarCubiculo();
        this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnCubiculoActionPerformed

    private void btnEspacioTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspacioTrabajoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);//para ocultar la ventana de los botones
        reservas.reservarEspacioTrabajo();
        this.setVisible(true);//para volver a mostas los botones
    }//GEN-LAST:event_btnEspacioTrabajoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuditorio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCubiculo;
    private javax.swing.JButton btnEspacioTrabajo;
    private javax.swing.JButton btnRecreacion;
    private javax.swing.JButton btnVerEstado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
